name: facial-enhancement-frontend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
    - streamlit==1.27.0
    - requests==2.31.0
    - pillow==10.0.1
    - python-dotenv==1.0.0
