name: facial-enhancement
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=23.0
  - pytorch=2.0.1
  - torchvision=0.15.2
  - cudatoolkit=11.8  # Only needed if using CUDA
  - pillow=10.0.1
  - numpy=1.24.3
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.23.2
    - python-multipart==0.0.6
    - pydantic==2.4.2
    - prometheus-fastapi-instrumentator==6.1.0
    - requests==2.31.0
    - python-dotenv==1.0.0
